👽 CRM Skills - stop using deprecated experience level field
SSWConsulting/SSW.People pull request #396
Opened 2022-05-06 07:40 UTC by wicksipedia

📄 README - updated getting started information

2022-05-06 07:46 UTC, bradystroud approved these changes

2022-05-09 00:33 UTC, bradystroud requested changes
Do we need `package-lock.json` when we are using Yarn?
Doesn't `yarn-lock.json` do the same job?

2022-05-09 00:40 UTC, wicksipedia commented
Yarn was listed as optional on the project - updated the README to make it a required tool
Removed and gitignored the `package-lock.json` since it isn't used

2022-05-09 00:43 UTC, bradystroud approved these changes

2022-05-09 00:47 UTC, merged