Added sitemap plugin to gatsby-config
SSWConsulting/SSW.People pull request #412
Opened 2022-07-21 07:46 UTC by ozairashfaqueSSW

#410 

- Added [gatsby-plugin-sitemap](https://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap/) to gatsby-config

2022-07-22 07:03 UTC, bradystroud requested changes

2022-07-22 07:03 UTC, bradystroud commented on gatsby-config.js
> +    'gatsby-plugin-sitemap',
Might need some configuration

> You probably do not want to use the defaults in this plugin

See https://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap/#recommended-usage

2022-07-22 07:03 UTC, bradystroud commented on package.json
> +    "gatsby": ">=1",
What does this do?
I think it would be better to lock it on a certain version as there could be breaking changes

2022-09-29 12:31 UTC, bradystroud commented
@ozairashfaqueSSW Can you give an update on this one?

2022-11-14 00:14 UTC, closed without merging

2022-11-15 00:51 UTC, ozairashfaqueSSW commented
Closing this PR because work has already been done. see issue https://github.com/SSWConsulting/SSW.People/pull/161