414 style people page restyle
SSWConsulting/SSW.People pull request #421
Opened 2022-07-28 05:32 UTC by Geordie88

I cleaned up the implementation of the view all link restyle by removing the unnecessary new class.

![image](https://user-images.githubusercontent.com/97079655/181427503-bcaf7f08-fb34-4f12-bea5-673d32f6ca6d.png)
figure: view all new positions

I removed the unnecessary new hr between the skill set and logos. I looked into placing the hr between the logos and primary content. After consulting with Brady, this is a dev task rather than a designer one.

2022-07-28 05:48 UTC, bradystroud approved these changes

2022-07-28 17:24 UTC, tiagov8 requested changes
@Geordie88 
1. Why another class?
2. Improve PR title

2022-08-03 00:41 UTC, Geordie88 commented
> @Geordie88
> 
> 1. Why another class?

I assume u are referring to the a.arrow-next. the link needed some top padding to be presentable, especially in the smaller screen sizes (phone etc).
  
> 2. Improve PR title
changed pr title 

from:
 style people page restyle

to:
style view all link restyle

2022-08-03 17:41 UTC, tiagov8 approved these changes

2022-08-03 18:12 UTC, tiagov8 commented
Hi @Geordie88 Geordie,

I recorded a video to show you a best way of doing this task: https://youtu.be/mdoxkF0s0mo

1. Please watch it carefully and let me know if in doubt

Hey @bradystroud 

1. Can you please let us know when these changes are live?

2022-08-05 04:16 UTC, merged