424 style make footer consistent with rules footer
SSWConsulting/SSW.People pull request #425
Opened 2022-08-03 06:38 UTC by Geordie88

cc: @adamcogan, @tiagov8

Hi Tiago,

As per our conversation I have restyled the Peoples footer so that it is consistent with the Rules footer. 

![image](https://user-images.githubusercontent.com/97079655/182536465-03740dff-9567-4a22-85cc-bf8a07aadab4.png)
**Figure: current People footer**

![image](https://user-images.githubusercontent.com/97079655/182536681-166510cc-5549-417d-b3f6-c51c0a124915.png)
**Figure: Updated peoples footer**

![image](https://user-images.githubusercontent.com/97079655/182536923-e149b9a7-3bdd-42b2-9196-c7fafb12b21f.png)
**Figure: rules footer**

I could not find an equivalent to https://github.com/SSWConsulting/SSW.Rules/releases/tag/20201117.1 for people so I did not add a link to the build version. 

You will note that in my updated version the build version number has been replaced with "#(VERSION DEPLOYED)" I have not made any changes to cause this so I believe that it is due to my local branch. (I consulted Jack P and he agreed)

2022-08-03 21:08 UTC, tiagov8 requested changes
Hi @Geordie88 

I am happy with the specific changes to the footer... however I am seeing the "bad" changes for the "view-all" link in this PR. More details: https://youtu.be/mdoxkF0s0mo

1. Please chase up @bradystroud and ask him what is the best way to keep your footer changes, but ignore crossed below in this PR:

<img width="978" alt="Screen Shot 2022-08-03 at 2 07 25 PM" src="https://user-images.githubusercontent.com/12601228/182712054-ae19c1c1-4cb4-48b9-941c-a79e6cc90d80.png">

2022-08-05 04:27 UTC, bradystroud commented
@tiagov8 waiting on your approval

2022-08-05 04:27 UTC, bradystroud approved these changes

2022-08-08 21:44 UTC, tiagov8 approved these changes

2022-08-08 21:44 UTC, merged

2022-08-08 21:45 UTC, tiagov8 commented
> @tiagov8 waiting on your approval

done