🐛 Fixed contributions calendar + updated all packages
SSWConsulting/SSW.People pull request #450
Opened 2022-11-28 22:56 UTC by BrookJeynes

#433

2022-11-28 23:00 UTC, bradystroud requested changes

2022-11-28 23:00 UTC, bradystroud commented on src/templates/person.js
> +// import { Widget } from 'ssw.rules.widget';
Comment the widget back in
```suggestion
import { Widget } from 'ssw.rules.widget';
```

2022-11-28 23:00 UTC, bradystroud commented on src/templates/person.js
> +  // eslint-disable-next-line no-unused-vars
Remove this
```suggestion
```

2022-11-28 23:00 UTC, bradystroud commented on src/templates/person.js
> +  // };
comment this back in

2022-11-28 23:00 UTC, bradystroud commented on src/templates/person.js
> +  // }, []);
Comment back in

2022-11-28 23:00 UTC, bradystroud commented on src/templates/person.js
> +            {/* <div className="flex justify-center hidden md:block ">
comment this back in

2022-11-28 23:00 UTC, bradystroud commented on src/templates/person.js
> +            </div> */}
comment this back in

2022-11-28 23:00 UTC, bradystroud commented on src/templates/person.js
> +            {/* <div className="md:hidden">{githubUsername && WidgetComponent}</div> */}
comment this back in

2022-11-28 23:00 UTC, bradystroud commented on site-config.js
> +// const path = require(`path`);
Remove this

2022-11-28 23:07 UTC, bradystroud commented
@BrookJeynes 
Pipeline is failing at `yarn lint` https://dev.azure.com/ssw/SSW.People/_build/results?buildId=41309&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=80694584-9a00-5514-2ba2-f6dabf815050

To fix
1. run `yarn lint --fix` locally. --fix auto fixes most issues, but sometimes you need to do some manually

2022-11-29 00:23 UTC, BrookJeynes commented
> @BrookJeynes Pipeline is failing at `yarn lint` https://dev.azure.com/ssw/SSW.People/_build/results?buildId=41309&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=80694584-9a00-5514-2ba2-f6dabf815050
> 
> To fix
> 
>     1. run `yarn lint --fix` locally. --fix auto fixes most issues, but sometimes you need to do some manually

Done - see latest commits

2022-11-29 03:51 UTC, bradystroud approved these changes

2022-11-29 03:51 UTC, merged