💄 Make Alumni Status Obvious
SSWConsulting/SSW.People pull request #612
Opened 2024-02-22 13:39 UTC by Aibono1225

Relates to https://github.com/SSWConsulting/SSW.People/issues/309

Added tag+icon next to the title on past employee's profile **(only for screen > 640px）**
![image](https://github.com/SSWConsulting/SSW.People/assets/127192800/07a758df-cdef-45a2-8a55-435bf4a1d83b)

2024-02-22 20:17 UTC, tiagov8 requested changes
Please see tasks in Conversation tab ;)

2024-02-22 20:17 UTC, tiagov8 commented
Hi @Aibono1225 

Thanks for that.

We don't want it to look like a button. To make it look more like a tag...

- [ ] 1. Please change the background to `#eee` and the text to `#cc4141`
- [ ] 2. I think it could be smaller... around 75% of what the CONTACT US button

We also don't want to hide it in small screens.

- [ ] 3. Please keep it and after implemented I will suggest further changes to the mobile view

2024-02-23 12:10 UTC, Aibono1225 commented
Hi @tiagov8 ,

Updated UI:

![image](https://github.com/SSWConsulting/SSW.People/assets/127192800/b10b0c9d-3121-4773-813d-966c1c785d54)
**Figure: Desktop view**

![image](https://github.com/SSWConsulting/SSW.People/assets/127192800/0fd1dfc7-889b-47cc-9e2b-b17af03a998a)
**Figure: Mobile view**

Please let me know if further changes are needed 😊

2024-02-23 23:44 UTC, tiagov8 approved these changes

2024-02-23 23:44 UTC, tiagov8 commented
LGTM

2024-02-25 23:31 UTC, JackDevAU approved these changes

2024-02-26 09:20 UTC, merged